version: "3.9"

services:
  db_master:
    image: mysql:8.0.13
    container_name: signle_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    ports:
      - "3306:3306"
    volumes:
      - ./conf:/etc/mysql
      - ./data:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files

