version: '3'

services:
  master:
    image: redis
    container_name: redis-master
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - ./master/conf:/etc/redis
      - ./master/data:/data
      - ./master/log:/log
    ports:
      - 6380:6379
    networks:
      redisNet:
        ipv4_address: 192.168.88.80

  follower1:
    image: redis
    container_name: redis-follower1
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - ./follower1/conf:/etc/redis
      - ./follower1/data:/data
      - ./follower1/log:/log
    ports:
      - 6381:6379
    networks:
      redisNet:
        ipv4_address: 192.168.88.81

  follower2:
    image: redis
    container_name: redis-follower2
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - ./follower2/conf:/etc/redis
      - ./follower2/data:/data
      - ./follower2/log:/log
    ports:
      - 6382:6379
    networks:
      redisNet:
        ipv4_address: 192.168.88.82


  sentinel1:
    image: redis
    depends_on:
      - master
      - follower1
      - follower2
    container_name: redis-sentinel1
    command: /bin/bash -c "redis-sentinel /etc/redis/redis-sentinel.conf"
    volumes:
      - ./sentinel1:/etc/redis
      - ./sentinel1/data:/data
      - ./sentinel1/log:/log
    ports:
      - 26379:26379
    networks:
      redisNet:
        ipv4_address: 192.168.88.83

  sentinel2:
    image: redis
    depends_on:
      - master
      - follower1
      - follower2
    container_name: redis-sentinel2
    command: /bin/bash -c "redis-sentinel /etc/redis/redis-sentinel.conf"
    volumes:
      - ./sentinel2:/etc/redis
      - ./sentinel2/data:/data
      - ./sentinel2/log:/log
    ports:
      - 26380:26379
    networks:
      redisNet:
        ipv4_address: 192.168.88.84

  sentinel3:
    image: redis
    depends_on:
      - master
      - follower1
      - follower2
    container_name: redis-sentinel3
    command: /bin/bash -c "redis-sentinel /etc/redis/redis-sentinel.conf"
    volumes:
      - ./sentinel3:/etc/redis
      - ./sentinel3/data:/data
      - ./sentinel3/log:/log
    ports:
      - 26381:26379
    networks:
      redisNet:
        ipv4_address: 192.168.88.85


networks:
  redisNet:
    external: true
