version: '3.6'

networks:
  zk-net:
    external: true

services:
  sentinel1:
    image: redis
    container_name: redis-sentinel-1
    restart: always
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26379:26379
    volumes:
      - ./sentinel1/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - zk-net

  sentinel2:
    image: redis
    container_name: redis-sentinel-2
    restart: always
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26380:26379
    volumes:
      - ./sentinel2/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - zk-net

  sentinel3:
    image: redis
    container_name: redis-sentinel-3
    restart: always
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26381:26379
    volumes:
      - ./sentinel3/conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    networks:
      - zk-net