version: '3.6'

networks:
  zk-net:
    name: zk-net

services:
  master:
    image: redis
    container_name: redis-master
    restart: always
    command: redis-server --port 6379  --appendonly yes
    ports:
      - 6380:6379
    volumes:
      - ./master/data:/data
    networks:
      - zk-net

  slave1:
    image: redis
    container_name: redis-slave-1
    restart: always
    command: redis-server --slaveof master 6379 --port 6379  --appendonly yes
    ports:
      - 6381:6379
    volumes:
      - ./slave1/data:/data
    networks:
      - zk-net


  slave2:
    image: redis
    container_name: redis-slave-2
    restart: always
    command: redis-server --slaveof master 6379 --port 6379  --appendonly yes
    ports:
      - 6382:6379
    volumes:
      - ./slave2/data:/data
    networks:
      - zk-net