version: '3'

networks:
  redis-net:
    name: redis-net

services:
  master:
    image: redis
    hostname: redis-master
    container_name: redis-master
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - ./master/conf:/etc/redis
      - ./master/data:/data
      - ./master/log:/log
    ports:
      - 6380:6379
    networks:
      - redis-net

  follower:
    image: redis
    hostname: redis-follower
    container_name: redis-follower
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    volumes:
      - ./follower/conf:/etc/redis
      - ./follower/data:/data
      - ./follower/log:/log
    ports:
      - 6381:6379
    networks:
      - redis-net

